### ISSUE TITLE
Create an event in Google Agenda

### ISSUE THREAD

**Issue by vaniaon** [edufysos/full-teaching-experiment#2]
Every time a user creates an event in Google Agenda, Full-Teaching should also create an event in his Google Agenda if the user is logged with Google Credentials

**Comment by goncazevedo** [comment]
Google agenda integration is possible by any students that are logged via google. The student has the option to sync its calendar to google agenda by clicking a button. If any new sessions are added after the synchronization, the student must synchronize it again.
